[package]
name = "nesse_emu"
version = "0.1.0"
authors = ["Daniel Boyle <boylede+github@gmail.com>"]
edition = "2018"

[dependencies]

[profile.release]
lto=true
codegen-units = 1
panic = 'abort'

[dev-dependencies]
# used by examples
crossterm = "0.19.0"
rand = "0.7"