[package]
name = "nesse_codegen"
version = "0.1.0"
authors = ["Daniel Boyle <boylede+github@gmail.com>"]
edition = "2018"

[dependencies]
codegen = "0.1.3"
time = "0.1.40"
select = "0.4.3"
serde = { version = "1.0", features = ["derive"]}
ron = "0.6"

